FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy code
COPY etl_tasks.py /app/etl_tasks.py
COPY schemas /app/schemas

ENV PYTHONUNBUFFERED=1
CMD ["python", "-c", "from etl_tasks import run_etl_from_minio_to_postgres; run_etl_from_minio_to_postgres('sample/orders_sample.csv')"]
